In [ ]:
import torch

In [ ]:
torch.cuda.is_available()

True

In [ ]:
A=torch.Tensor([[1,2,3],
                [1,1,1],
                [1,7,4]]).cuda()
B=torch.Tensor([[1,1,3],
                [1,8,1],
                [5,4,5]]).cuda()


In [ ]:
A*B

tensor([[ 1.,  2.,  9.],
        [ 1.,  8.,  1.],
        [ 5., 28., 20.]], device='cuda:0')

In [ ]:
A@B

tensor([[18., 29., 20.],
        [ 7., 13.,  9.],
        [28., 73., 30.]], device='cuda:0')

In [ ]:
Q_table = torch.Tensor([[5,4,1],
                        [1,2,7],
                        [14,4,7]])

In [ ]:
Best_Action=torch.argmax(Q_table,dim=1)
Best_Action

tensor([0, 2, 0])

In [ ]:
Val_fn,Best_Action=torch.max(Q_table,dim=1)
print(Val_fn,Best_Action)

tensor([ 5.,  7., 14.]) tensor([0, 2, 0])


In [ ]:
N,D=3,4

x=torch.rand(N,D,requires_grad=True)
y=torch.rand(N,D,requires_grad=True)
z=torch.rand(N,D,requires_grad=True)

a=x*y
b=3*a+z
c=b.sum()

c.backward()
print(x.grad)
print(y.grad)
print(z.grad)
print(a.grad)


tensor([[1.9193, 0.7321, 1.5595, 0.4617],
        [0.6514, 1.0124, 2.7804, 1.2418],
        [1.3159, 0.7046, 1.3691, 1.6086]])
tensor([[1.8087, 2.5834, 2.9659, 1.6832],
        [1.3484, 1.3474, 0.8501, 2.3330],
        [0.9053, 1.6346, 1.7649, 1.2356]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
None


<ipython-input-29-857f7d257efe>:15: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at aten/src/ATen/core/TensorBody.h:489.)
  print(a.grad)


In [ ]:
c.backward()

RuntimeError: Trying to backward through the graph a second time (or directly access saved tensors after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved tensors after calling backward.

In [ ]:
N,D=3,4

x=torch.rand(N,D,requires_grad=True)
y=torch.rand(N,D,requires_grad=True)
z=torch.rand(N,D,requires_grad=True)

a=x*y
b=3*a+z
c=b.sum()

grad_b_wrt_a = torch.autograd.grad(b.sum(),a,retain_graph=True)
print(grad_b_wrt_a)



(tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]),)


In [ ]:
c.backward()